app_settings:
  app_type: "connector" # only lowercase letters, numbers, and underscores are allowed, e.g. salesforce, sap, zoho_crm, etc.
  app_name: "Google Sheet"
  app_icon_svg_url: "https://upload.wikimedia.org/wikipedia/commons/3/30/Google_Sheets_logo_%282014-2020%29.svg" # this is the icon of the app, should be a URL pointing to a SVG file.
  app_description: "Connector Example App"
  routes_directory: "src/modules" # this is the directory where the modules are located.

local_development_settings:
  sentry_dsn: ""
  cors_origins: ["*"]
  routes_directory: "src/modules"
  debug: true
  host: "0.0.0.0"
  port: 2003
